# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 3001, host: 3001
  # config.vm.network "forwarded_port", guest: 3002, host: 3002
  # config.vm.network "forwarded_port", guest: 6001, host: 6001
  # config.vm.network "forwarded_port", guest: 6002, host: 6002
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.network "private_network", ip: "33.33.33.2"

  config.vm.synced_folder "../../project", "/home/vagrant/project"

  config.vm.provision "shell", path: "script/provision.sh"

end
